### ISSUE TITLE
Some jobs missing after updating from 0.4.1 to v1.0.0

### ISSUE THREAD

**Issue by Musambani** [opencv/cvat#1632]
### My actions before raising this issue
- [x ] Read/searched [the docs](https://github.com/opencv/cvat/tree/master#documentation)
- [ x] Searched [past issues](/issues)

Hi all,

I have CVAT running inside a docker on amazon ec2 instance. For data storage there is an additional volume mounted.
everything worked smooth with version 0.5
before updating to 1.0 I cloned the instance and tried the update there. 
I pulled from git and afterwards did a docker-compose build.
After some attemts everything worked fine on the cloned instance.
I repeated the same on the original instance. (git pull, docker-compose down, docker-compose build, docker-compose up -d)
Because I had issues with the login I reverted back to the older version to see if I messed up.
Everything was still there.
In the next attempt I did a docker-compose build and overcame the login issues (apparently something was wrong in docker-compose.override.yml).
However after changing to 1.0 many tasks (maybe 50%) appear "empty". They are still listed in the UI, but do not show a preview. When trying to open a job (either new UI or old UI) the error "Error during fetching a job" is displayed. 
Browser console sais:
`:8080/api/v1/tasks/333/data/meta:1 Failed to load resource: the server responded with a status of 500 (Internal Server Error)
cvat-app.tsx:192 Error: Request failed with status code 500. "<h1>Server Error (500)</h1>"`
when switching back to 0.5 all tasks are gone.
Any ideas on what went wrong? Thanks!

**Comment by azhavoro** [comment]
Hi, v1.0.0 has completely different data structure(new folder structure, video and zip chunks instead of images, etc) layout and database schema, so migration from v0.5 to v1.0.0 may takes a lot of time(depends on number of task and tasks size). During migration process backend server is unavailable and you cannot login. Also it's impossible to downgrade from 1.0.0 to v.0.5. 
Could you attach migration log file (`/home/django/logs/migrations/0024_auto_20191023_1025.log` in `cvat` container).

**Comment by azhavoro** [comment]
In your log I see many exceptions like `FileExistsError: [Errno 17] File exists: '/home/django/data/data/72/compressed/0.zip'` this happened when you interrupted and started the migration process several times. In your case, I propose to clone the original instance and wait for the migration process to complete. You can view the migration progress with `docker logs cvat -f`

**Comment by Musambani** [comment]
is there a way how I can manually restart the migration process for some of the broken jobs? cloning the instance is not preferred as the instance would lose it's IP address.

**Comment by azhavoro** [comment]
It's not so easy, but you can copy all docker data folder `/var/lib/docker` from old instance and rebuild images for v1.0.0 as usual.

**Comment by Musambani** [comment]
ok, that would work. In the meanwhile I think I found files regarding these tasks in /data/suspicious_tasks
does this make sense? Can I run some migration skript there?

**Comment by azhavoro** [comment]
Lets try to migrate first. There are folders that have no corresponding records in your database by some reasons, so they cannot be migrated.

**Comment by Musambani** [comment]
well... the backup instance is already migrated. Should I launch a third instance from the v0.5 backup or is it easier to copy the migrated tasks from the backup instance? thanks
