### PR TITLE
Fix issue with LDAP not working due to function mismatch

### LINKED ISSUE #9382: LDAP: Could not login on the server - django_auth_ldap: create_user()
### Actions before raising this issue

- [x] I searched the existing issues and did not find anything similar.
- [x] I read/searched [the docs](https://docs.cvat.ai/docs/)

### Steps to Reproduce

1. Configure LDAP connection (as showed in the docs).
2. Try to login...

Error ->

Image

### Expected Behavior

Should have logged in.

### Possible Solution

Possible issue when migrating from version 2.32.0 to 2.33.0

### Context

After migrating from version 2.28.0 to 2.35.0, I tried logging in with my usual credentials and encountered the same issue.

The full error displayed is as follows:
```log
cvat_server                  | [2025-05-01 15:45:51,772] WARNING django_auth_ldap: create_user() missing 2 required positional arguments: 'created' and 'raw' while authenticating cvat.admin                                                                                                                                                                                 
cvat_server                  | 
cvat_server                  | 2025-05-01 15:45:52,187 DEBG 'uvicorn-0' stderr output:                                                                                                 
cvat_server                  | [2025-05-01 15:45:51,918] ERROR django.request: Internal Server Error: /api/auth/login
cvat_server                  | Traceback (most recent call last):                                                                                                                      
cvat_server                  |   File "/opt/venv/lib/python3.10/site-packages/asgiref/sync.py", line 518, in thread_handler                                                            
cvat_server                  |     raise exc_info[1]                                                                                                                                   
cvat_server                  |   File "/opt/venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 42, in inner                                                    
cvat_server                  |     response = await get_response(request)                                                                                                              
cvat_server                  |   File "/opt/venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 253, in _get_response_async                                          
cvat_server                  |     response = await wrapped_callback(                                                                                                                  
cvat_server                  |   File "/opt/venv/lib/python3.10/site-packages/asgiref/sync.py", line 468, in __call__                                                                  
cvat_server                  |     ret = await asyncio.shield(exec_coro)                                                                                                               
cvat_server                  |   File "/opt/venv/lib/python3.10/site-packages/asgiref/current_thread_executor.py", line 40, in run                                                     
cvat_server                  |     result = self.fn(*self.args, **self.kwargs)
traefik                      | {"ClientHost":"172.18.0.8","DownstreamContentSize":145,"DownstreamStatus":500,"Duration":1154018505,"RequestHost":"cvat.picudo-rojo-desarrollo.org","RequestMethod":"POST","RequestPath":"/api/auth/login?org=","RequestPort":"-","RequestProtocol":"HTTP/1.1","RouterName":"cvat@docker","StartUTC":"2025-05-01T15:45:51.04616834Z","level":"info","msg":"","time":"2025-05-01T15:45:52Z"}
cvat_server                  |   File "/opt/venv/lib/python3.10/site-packages/asgiref/sync.py", line 522, in thread_handler
cvat_server                  |     return func(*args, **kwargs)                                                                                                                        
cvat_server                  |   File "/opt/venv/lib/python3.10/site-packages/django/views/decorators/csrf.py", line 56, in wrapper_view                                               
cvat_server                  |     return view_func(*args, **kwargs)                                                                                                                   
cvat_server                  |   File "/opt/venv/lib/python3.10/site-packages/django/views/generic/base.py", line 104, in view
cvat_server                  |     return self.dispatch(request, *args, **kwargs)                                                                                                      
cvat_server                  |   File "/opt/venv/lib/python3.10/site-packages/django/utils/decorators.py", line 46, in _wrapper                                                        
cvat_server                  |     return bound_method(*args, **kwargs)                                                                                                                
cvat_server                  |   File "/opt/venv/lib/python3.10/site-packages/django/views/decorators/debug.py", line 92, in sensitive_post_parameters_wrapper                         
cvat_server                  |     return view(request, *args, **kwargs)                                                                                                               
cvat_server                  |   File "/opt/venv/lib/python3.10/site-packages/dj_rest_auth/views.py", line 48, in dispatch                                                             
cvat_server                  |     return super().dispatch(*args, **kwargs)                                                                                                            
cvat_server                  |   File "/opt/venv/lib/python3.10/site-packages/rest_framework/views.py", line 509, in dispatch                                                          
cvat_server                  |     response = self.handle_exception(exc)                                                                                                               
cvat_server                  |   File "/opt/venv/lib/python3.10/site-packages/rest_framework/views.py", line 469, in handle_exception                                                  
cvat_server                  |     self.raise_uncaught_exception(exc)                                                                                                                  
cvat_server                  |   File "/opt/venv/lib/python3.10/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception                                          
cvat_server                  |     raise exc                                                                                                                                           
cvat_server                  |   File "/opt/venv/lib/python3.10/site-packages/rest_framework/views.py", line 506, in dispatch                                                          
cvat_server                  |     response = handler(request, *args, **kwargs)                                                                                                        
cvat_server                  |   File "/home/django/cvat/apps/iam/views.py", line 105, in post                                                                                         
cvat_server                  |     self.login()                                                                                                                                        
cvat_server                  |   File "/opt/venv/lib/python3.10/site-packages/dj_rest_auth/views.py", line 66, in login                                                                
cvat_server                  |     self.user = self.serializer.validated_data['user']                                                                                                  
cvat_server                  |   File "/opt/venv/lib/python3.10/site-packages/rest_framework/serializers.py", line 267, in validated_data                                              
cvat_server                  |     raise AssertionError(msg)                                                                                                                           
cvat_server                  | AssertionError: You must call `.is_valid()` before accessing `.validated_data`.                                                                         
cvat_server                  |                                                                                                                                                         
cvat_server                  | 2025-05-01 15:45:52,195 DEBG 'uvicorn-0' stdout output:                                                                                                 
cvat_server                  | [2025-05-01 15:45:52,194] INFO:     172.18.0.8:0 - "POST /api/auth/login?org= HTTP/1.0" 500 Internal Server Error
```

I had no issues in version 2.28.0.

However, I was able to trace the issue back to version 2.33.0. I tested it in version 2.32.0 and it worked perfectly, but in version 2.33.0 it no longer worked.

Specifically, the issue may be in `cvat/apps/iam/signals.py`.

The following was introduced in version 2.33.0:

```python
elif settings.IAM_TYPE == "LDAP":

    def create_user(sender, created: bool, raw: bool, user=None, ldap_user=None, **kwargs):
        if created and raw:
            return
```

My overlay (that work's on v2.32.0) settings is:
```python
# Overlaying production
from cvat.settings.production import *

# Custom code below
import ldap
from django_auth_ldap.config import LDAPSearch, GroupOfUniqueNamesType

if os.environ.get("CSRF_TRUSTED_ORIGINS"):
    CSRF_TRUSTED_ORIGINS = os.environ.get("CSRF_TRUSTED_ORIGINS", "").split(",")

try:
    CVAT_LDAP_USER = os.environ["CVAT_LDAP_USER"]
    CVAT_LDAP_PASSWORD = os.environ["CVAT_LDAP_PASSWORD"]
except KeyError:
    print("Environment variable does not exist")

# Notify CVAT that we are using LDAP authentication
IAM_TYPE = "LDAP"

# Talking to the LDAP server
AUTH_LDAP_SERVER_URI = os.environ.get("AUTH_LDAP_SERVER_URI", "ldap://lldap:3890")  # IP Addresses also work
ldap.set_option(ldap.OPT_REFERRALS, 0)


_BASE_DN = "DC=localhost,DC=local"
_PEOPLE_OU = "OU=people"
_GROUP_OU = "OU=groups"
_PEOPLE_DN = "%s,%s" % (_PEOPLE_OU, _BASE_DN)
_GROUP_DN = "%s,%s" % (_GROUP_OU, _BASE_DN)

# Authenticating with the LDAP server
AUTH_LDAP_BIND_DN = "CN=%s,%s" % (CVAT_LDAP_USER, _PEOPLE_DN)
AUTH_LDAP_BIND_PASSWORD = CVAT_LDAP_PASSWORD

AUTH_LDAP_USER_SEARCH = LDAPSearch(_BASE_DN, ldap.SCOPE_SUBTREE, "(uid=%(user)s)")

AUTH_LDAP_GROUP_SEARCH = LDAPSearch(
    _GROUP_DN, ldap.SCOPE_SUBTREE, "(objectClass=groupOfUniqueNames)"
)

print("AUTH_LDAP_GROUP_SEARCH", AUTH_LDAP_GROUP_SEARCH)
print("AUTH_LDAP_USER_SEARCH", AUTH_LDAP_USER_SEARCH)

# Mapping Django field names to FreeIPA attributes
AUTH_LDAP_USER_ATTR_MAP = {
    "user_name": "uid",
    "first_name": "first_name",
    "last_name": "last_name",
    "email": "mail",
}

AUTH_LDAP_ALWAYS_UPDATE_USER = True

# Cache group memberships for an hour to minimize LDAP traffic
AUTH_LDAP_CACHE_GROUPS = True
AUTH_LDAP_GROUP_CACHE_TIMEOUT = 3600
AUTH_LDAP_AUTHORIZE_ALL_USERS = False

# Group Management
AUTH_LDAP_GROUP_TYPE = GroupOfUniqueNamesType(name_attr="cn")

# Register Django LDAP backend
AUTHENTICATION_BACKENDS += ["django_auth_ldap.backend.LDAPBackend"]

# Map FreeIPA groups to Django/CVAT groups.
AUTH_LDAP_ADMIN_GROUPS = [
    "CN=cvat_admins,%s" % _GROUP_DN,
]
AUTH_LDAP_WORKER_GROUPS = [
    "CN=cvat_workers,%s" % _GROUP_DN,
]
AUTH_LDAP_USER_GROUPS = [
    "CN=cvat_users,%s" % _GROUP_DN,
]

DJANGO_AUTH_LDAP_GROUPS = {
    "admin": AUTH_LDAP_ADMIN_GROUPS,
    "user": AUTH_LDAP_USER_GROUPS,
    "worker": AUTH_LDAP_WORKER_GROUPS,
}
```

### Environment

```Markdown
- CVAT version: 2.35.0
- Docker compose
- LLDAP
```

### PR DESCRIPTION
**Pull request by Kira-Kitsune**
### Motivation and context
Resolves #9382 
I have ran into the same issue, I have done some searching and saw that the LDAP `create_user` was changed in #9272 for the LDAP implementation to have two new arguments `created` and `raw` which is not needed in the [Django LDAP Authentication](https://github.com/django-auth-ldap/django-auth-ldap/blob/master/django_auth_ldap/backend.py), I think the change was just meant to fall in line with the [django post_save signal](https://docs.djangoproject.com/en/5.1/ref/signals/#django.db.models.signals.post_save)

### How has this been tested?

I removed the lines and rebuilt and tried logging in with LDAP and it succeed.

### Checklist

- [x] I submit my changes into the `develop` branch
- [x] I have created a changelog fragment 
- [ ] ~~I have updated the documentation accordingly~~
- [ ] ~~I have added tests to cover my changes~~
- [x] I have linked related issues (see [GitHub docs](
  https://help.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword))

### License

- [x] I submit _my code changes_ under the same [MIT License](
  https://github.com/cvat-ai/cvat/blob/develop/LICENSE) that covers the project.
  Feel free to contact the maintainers if that's a concern.

### CODE REVIEW

**Comment by azhavoro** [comment]
@Kira-Kitsune Thank you for the contribution!

Could you add a note to the changelog? https://github.com/cvat-ai/cvat/blob/develop/CHANGELOG.md?plain=1#L9-L14

File: cvat/apps/iam/signals.py [hunk 1]
```diff
@@ -38,10 +38,7 @@ def create_user(sender, instance, created: bool, raw: bool, **kwargs):
 
 elif settings.IAM_TYPE == "LDAP":
 
-    def create_user(sender, created: bool, raw: bool, user=None, ldap_user=None, **kwargs):
-        if created and raw:
-            return
-
+    def create_user(sender, user=None, ldap_user=None, **kwargs):
```
Comment (SpecLad) [inline cvat/apps/iam/signals.py:41]: The `created` and `raw` parameters are still needed, because the same function is also used as the handler for the `post_save` signal. I suggest you put them back, but add default values, so that the function can handle both signals.

Comment (Kira-Kitsune) [reply cvat/apps/iam/signals.py:41]: From what I could tell, it only creates the function it needs depending on the type of login, post_save is never used when it's LDAP as it never reaches that case when configured to LDAP, I could be wrong of course.

Comment (SpecLad) [reply cvat/apps/iam/signals.py:41]: I'm talking about the case when LDAP is not enabled.

Comment (Kira-Kitsune) [reply cvat/apps/iam/signals.py:41]: When LDAP is not enabled the create_user function still has the arguments

Comment (SpecLad) [reply cvat/apps/iam/signals.py:41]: Ah, my bad. I missed that this function was defined conditionally.

File: changelog.d/20250624_141940_kira.pearce_LDAP_Fix.md [hunk 2]
```diff
@@ -0,0 +1,4 @@
+### Fixed
+
+Fixed LDAP as an issue was formed with the wrong arguments being apart of the function definition
+  (<https://github.com/cvat-ai/cvat/pull/9478>)
```
Comment (azhavoro) [inline changelog.d/20250624_141940_kira.pearce_LDAP_Fix.md]:
```suggestion
- Fixed LDAP as an issue was formed with the wrong arguments being apart of the function definition
  (<https://github.com/cvat-ai/cvat/pull/9478>)
```
