### PR TITLE
Remove URL signing

### LINKED ISSUE #7755: api/auth/signing not working properly
### Actions before raising this issue

- [X] I searched the existing issues and did not find anything similar.
- [X] I read/searched [the docs](https://docs.cvat.ai/docs/)

### Steps to Reproduce

Submitting a POST request to api/auth/signing results in the following error:

```
2024-04-12T00:29:25.585362846Z   File "/opt/venv/lib/python3.10/site-packages/rest_framework/views.py", line 332, in check_permissions
2024-04-12T00:29:25.585365972Z     if not permission.has_permission(request, self):
2024-04-12T00:29:25.585369104Z   File "/home/django/cvat/apps/iam/permissions.py", line 2032, in has_permission
2024-04-12T00:29:25.585372323Z     if not view.detail:
2024-04-12T00:29:25.585375258Z AttributeError: 'SigningView' object has no attribute 'detail'
```

### Expected Behavior

The method is supposed to return a string (signed URL).

### Possible Solution

N/A

### Context

Capture

### Environment

```Markdown
https://app.cvat.ai/
```

### PR DESCRIPTION
**Pull request by SpecLad**
### Motivation and context

The `/api/auth/signing` endpoint always returns a 500 code. This is because `PolicyEnforcer.has_permission` checks `view.detail` as the first step, which doesn't exist for `SigningView`, as it is not a viewset.

This has been broken at least since 4708b5ec, when `PolicyEnforcer` was introduced. It could potentially be fixed; however, I see no clear use case for this feature, plus it has no tests or documentation. Given that it lies in a security-critical area, I would rather reduce our attack surface by removing it entirely.

This also lets us remove a dependency.

Closes #7755.

### Checklist

- [x] I submit my changes into the `develop` branch
- [x] I have created a changelog fragment 
- ~~[ ] I have updated the documentation accordingly~~
- ~~[ ] I have added tests to cover my changes~~
- ~~[ ] I have linked related issues (see [GitHub docs](
  https://help.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword))~~

### License

- [x] I submit _my code changes_ under the same [MIT License](
  https://github.com/cvat-ai/cvat/blob/develop/LICENSE) that covers the project.
  Feel free to contact the maintainers if that's a concern.

### CODE REVIEW

**Comment by nmanovic** [comment]
I agree. @bsekachev , your thoughts?
